config/routes.rb
Rails.application.routes.draw do
  root "authentications#new"
  resource :authentication, only: [:new, :create, :destroy]
  resources :fellows
  resources :lendings
  resources :users, except: :index
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fellow.rb
class Fellow < ApplicationRecord
  belongs_to :friend, class_name: "User"
  belongs_to :user

  before_validation :set_friend_connect, if: :friend_email
  attribute :friend_email, :string
  validate :friend_email_check, if: :friend_email

	def relationship
    if self.friend
      if self.friend.friends.find_by(id: self.user.id).present?
        status = "<-->　双方向関係"
      else
        status = "+-->　相手の関係がありません"      
      end
    else
      status = "相手が不明になりました"
    end
    status
	end

  private
  def set_friend_connect
    if friend_user = User.find_by(email: self.friend_email.downcase)
      self.friend_id = friend_user.id
    end
  end

  def friend_email_check
    if self.user.email == friend_email
      errors.add(:friend_email, "自身のメールアドレスです")
    elsif self.user.friends.where(email: friend_email).present?
      errors.add(:friend_email, "既に登録済みです")
    end
  end

end

app/models/lending.rb
class Lending < ApplicationRecord
  belongs_to :lender, class_name: "User"
  belongs_to :borrower, class_name: "User"
end

app/models/lending_history.rb
class LendingHistory < ApplicationRecord
  belongs_to :lender
  belongs_to :borrower
end

app/models/user.rb
class User < ApplicationRecord
	has_many :lendings, foreign_key: "lender_id"
	has_many :borrowings, foreign_key: "borrower_id", class_name: "Lending"
	has_many :fellows
	has_many :friends, through: :fellows, foreign_key: "friend_id"

	before_validation { email.downcase! }
	has_secure_password
	# has_secure_password :recovery_password, validations: false
  # attr_accessor :password_digest, :recovery_password_digest
	validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: true
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include AuthenticationsHelper
	before_action :authentication_check

  private
	def authentication_check
		unless logged_in?
			redirect_to new_authentication_path
		end
	end

	def restrict_action_in_logged
		if logged_in?
			redirect_to current_user
		end
	end	
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  skip_before_action :authentication_check, except: :destroy
  before_action :restrict_action_in_logged, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: params[:authentication][:email].downcase)
    if user && user.authenticate(params[:authentication][:password]) 
      session[:user_id] = user.id
      redirect_to user_path(user), notice: "ログインできました"
    else
      flash[:notice] =  "認証できません"
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to new_authentication_path
  end
end

app/controllers/fellows_controller.rb
class FellowsController < ApplicationController
  before_action :set_fellow, only: %i[ show edit update destroy ]

  def index
    # @fellows = Fellow.all
    @fellows = current_user.fellows
  end

  def show
    @fellow.relationship
  end

  def new
    # @fellow = Fellow.new
    @fellow = current_user.fellows.new
  end

  def edit
  end

  def create
    # @fellow = Fellow.new(fellow_params)
    @fellow = current_user.fellows.new(fellow_params)
    if @fellow.save
      redirect_to @fellow, notice: "Fellow was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @fellow.update(fellow_params)
      redirect_to @fellow, notice: "Fellow was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @fellow.destroy
    redirect_to fellows_url, notice: "Fellow was successfully destroyed."
  end

  private
    def set_fellow
      @fellow = Fellow.find(params[:id])
    end

    def fellow_params
      params.require(:fellow).permit(:friend_id, :own_id, :reason_of, :relation_since, :friend_email)
    end
end

app/controllers/lendings_controller.rb
class LendingsController < ApplicationController
  before_action :set_lending, only: %i[ show edit update destroy ]

  def index
    @lendings = current_user.lendings
    @borrowings = current_user.borrowings
  end

  def show
  end

  def new
    @lending = current_user.lendings.new
  end

  def edit
  end

  def create
    @lending = current_user.lendings.new(lending_params)

    respond_to do |format|
      if @lending.save
        format.html { redirect_to @lending, notice: "Lending was successfully created." }
        format.json { render :show, status: :created, location: @lending }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lending.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @lending.update(lending_params)
        format.html { redirect_to @lending, notice: "Lending was successfully updated." }
        format.json { render :show, status: :ok, location: @lending }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lending.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @lending.destroy
    respond_to do |format|
      format.html { redirect_to lendings_url, notice: "Lending was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_lending
      @lending = Lending.find(params[:id])
    end

    def lending_params
      params.require(:lending).permit(:item_name, :lending_at, :expected_return_at, :return_style, :lender_id, :borrower_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authentication_check, only: [:new, :create]
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :restrict_action_in_logged, only: [:new, :create]

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to new_authentication_path, notice: "User was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "User was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    redirect_to new_authentication_path, notice: "User was successfully destroyed."
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		current_user.present?
	end

end

app/views/application/_header.html.erb
<header>
	<ul>
		<% if logged_in? %>
			<li><%= link_to "マイページ", user_path(current_user) %></li>
			<li><%= link_to "仲間登録", new_fellow_path %></li>
			<li><%= link_to "仲間一覧", fellows_path %></li>
			<li><%= link_to "貸出し", new_lending_path %></li>
			<li><%= link_to "貸出一覧", lendings_path %></li>
			<li><%= link_to "ログアウト", authentication_path, method: :delete %></li>
		<% else%>
			<li><%= link_to "ログイン", new_authentication_path %></li>
		<% end %>
	</ul>
</header>

app/views/authentications/new.html.erb
<h1>Login</h1>
<p id="notice"><%= notice %></p>
<%= form_with(scope: :authentication, local: true, url: authentication_path) do |form| %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>


  <div class="actions">
    <%= form.submit "login" %>
  </div>
<% end %>
<br>
<%= link_to "ユーザ新規登録", new_user_path %>

app/views/fellows/_form.html.erb
<%= form_with(model: fellow, local: true) do |form| %>
  <% if fellow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fellow.errors.count, "error") %> prohibited this fellow from being saved:</h2>

      <ul>
        <% fellow.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%# byebug %>
    <% if fellow.friend_id %>
      <%= fellow.friend.name %>::<%= fellow.friend.email %>
    <% else %>
      <%= form.label :friend_email %>
      <%= form.text_field :friend_email %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :reason_of %>
    <%= form.text_area :reason_of %>
  </div>

  <div class="field">
    <%= form.label :relation_since %>
    <%= form.date_select :relation_since, start_year: 1950 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fellows/edit.html.erb
<h1>Editing Fellow</h1>

<%= render 'form', fellow: @fellow %>

<%= link_to 'Show', @fellow %> |
<%= link_to 'Back', fellows_path %>

app/views/fellows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fellows</h1>

<table>
  <thead>
    <tr>
      <th>name</th>
      <th>email</th> 
      <th>Reason of</th>
      <th>Relation since</th>
      <th>relationship</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fellows.each do |fellow| %>
      <tr>
        <td><%= fellow.friend.name if fellow.friend %></td>
        <td><%= fellow.friend.email if fellow.friend %></td> 
        <td><%= fellow.reason_of %></td>
        <td><%= fellow.relation_since %></td>
        <td><%= fellow.relationship %></td>
        <td><%= link_to 'Show', fellow %></td>
        <td><%= link_to 'Edit', edit_fellow_path(fellow) %></td>
        <td><%= link_to 'Destroy', fellow, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fellow', new_fellow_path %>

app/views/fellows/new.html.erb
<h1>New Fellow</h1>

<%= render 'form', fellow: @fellow %>

<%= link_to 'Back', fellows_path %>

app/views/fellows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Friend:</strong>
  <% user = User.find(@fellow.friend_id) %>
  <% if user.present? %>
    <%= user.name %>::<%= user.email %>
  <% end %>
</p>
<p>
  <strong>Reason of:</strong>
  <%= @fellow.reason_of %>
</p>
<p>
  <strong>Relation since:</strong>
  <%= @fellow.relation_since %>
</p>
<p>
  <strong>relationship:</strong>
  <%= @fellow.relationship %>
</p>

<%= link_to 'Edit', edit_fellow_path(@fellow) %> |
<%= link_to 'Back', fellows_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LendingManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "header" %>
    <%= yield %>
  </body>
</html>

app/views/lendings/_detail.html.erb
<table>
  <thead>
    <tr>
      <th>Item Name</th>
      <th>Lending at</th>
      <th>Expected return at</th>
      <% if side == "borrower" %>
        <th>Lender</th>
      <% else%>
        <th>Borrower</th>
      <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% dealings.each do |lending| %>
      <tr>
        <td><%= lending.item_name %></td>
        <td><%= lending.lending_at %></td>
        <% if lending.expected_return_at >= Time.now %>
          <td><%= lending.expected_return_at %></td>
        <% else%>
          <td class="limit_exceeded"><%= lending.expected_return_at %></td>   
        <% end %>
        <% if side == "borrower" %>
          <td><%= lending.lender.name %></td>
        <% else%>
          <td><%= lending.borrower.name %></td>
        <% end %>
        <td><%= link_to 'Show', lending %></td>
        <td><%= link_to 'Edit', edit_lending_path(lending) %></td>
        <td><%= link_to 'Destroy', lending, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/lendings/_form.html.erb
<%= form_with(model: lending, local: true) do |form| %>
  <% if lending.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lending.errors.count, "error") %> prohibited this lending from being saved:</h2>

      <ul>
        <% lending.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :item_name %>
    <%= form.text_field :item_name %>
  </div>

  <div class="field">
    <%= form.label :lending_at %>
    <%= form.date_select :lending_at %>
  </div>

  <div class="field">
    <%= form.label :expected_return_at %>
    <%= form.date_select :expected_return_at, default: Time.now + 7.days %>
  </div>

  <div class="field">
    <%= form.label :return_style %>
    <%= form.text_field :return_style %>
  </div>
  
  <div class="field">
    <%= form.label :borrower_id %>
    <%= form.collection_select :borrower_id, current_user.friends, :id, :email, selected: lending.borrower_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lendings/edit.html.erb
<h1>Editing Lending</h1>

<%= render 'form', lending: @lending %>

<%= link_to 'Show', @lending %> |
<%= link_to 'Back', lendings_path %>

app/views/lendings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lendings</h1>

<%= render "detail", dealings: @lendings, side: "lender" %>

<br>
<h1>Borrowings</h1>

<%= render "detail", dealings: @borrowings, side: "borrower" %>

<br>
<%= link_to 'New Lending', new_lending_path %>

app/views/lendings/new.html.erb
<h1>New Lending</h1>

<%= render 'form', lending: @lending %>

<%= link_to 'Back', lendings_path %>

app/views/lendings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lending.item_name %>
</p>

<p>
  <strong>Lending at:</strong>
  <%= @lending.lending_at %>
</p>

<p>
  <strong>Expected return at:</strong>
  <% if @lending.expected_return_at >= Time.now %>
    <span><%= @lending.expected_return_at %></span>
  <% else%>
    <span class="limit_exceeded"><%= @lending.expected_return_at %></span>
  <% end %>
</p>


<p>
  <strong>Return Style:</strong>
  <%= @lending.return_style %>
</p>

<p>
  <strong>Lender:</strong>
  <%= @lending.lender.name %>:<%= @lending.lender.email %>
</p>

<p>
  <strong>Borrower:</strong>
  <%= @lending.borrower.name %>:<%= @lending.borrower.email %>
</p>

<%= link_to 'Edit', edit_lending_path(@lending) %> |
<%= link_to 'Back', lendings_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
    <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %>
<br>
<%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' } %>